### ISSUE TITLE
Projekt positions können manchmal nicht gelöscht werden.

### ISSUE THREAD

**Issue by dacin21** [stiftungswo/better-dime#464]
Reporter:

Daniel R.

---

In https://<dime>/projects/311 können die project positions "Broschüre ..., Verkauf" nicht gelöscht werden, auch wenn diese keine project efforts mehr haben.

Sentry log;
```
ActiveRecord::DeleteRestrictionError: Cannot delete record because of dependent invoice_position
  from active_record/associations/has_one_association.rb:12:in `handle_dependency'
  from active_record/associations/builder/association.rb:129:in `block in add_destroy_callbacks'
  from active_support/callbacks.rb:429:in `instance_exec'
  from active_support/callbacks.rb:429:in `block in make_lambda'
  from active_support/callbacks.rb:201:in `block (2 levels) in halting'
  from active_support/callbacks.rb:607:in `block (2 levels) in default_terminator'
  from active_support/callbacks.rb:606:in `catch'
  from active_support/callbacks.rb:606:in `block in default_terminator'
  from active_support/callbacks.rb:202:in `block in halting'
  from active_support/callbacks.rb:514:in `block in invoke_before'
  from active_support/callbacks.rb:514:in `each'
  from active_support/callbacks.rb:514:in `invoke_before'
  from active_support/callbacks.rb:134:in `run_callbacks'
  from active_support/callbacks.rb:827:in `_run_destroy_callbacks'
  from active_record/callbacks.rb:309:in `destroy'
  from active_record/transactions.rb:311:in `block in destroy'
  from active_record/transactions.rb:375:in `block in with_transaction_returning_status'
  from active_record/connection_adapters/abstract/database_statements.rb:279:in `transaction'
  from active_record/transactions.rb:212:in `transaction'
  from active_record/transactions.rb:366:in `with_transaction_returning_status'
  from active_record/transactions.rb:311:in `destroy'
  from active_record/persistence.rb:551:in `destroy!'
  from active_record/associations/has_many_association.rb:100:in `each'
  from active_record/associations/has_many_association.rb:100:in `delete_records'
  from active_record/associations/collection_association.rb:385:in `remove_records'
  from active_record/associations/collection_association.rb:376:in `block in delete_or_destroy'
  from active_record/associations/collection_association.rb:135:in `block in transaction'
  from active_record/connection_adapters/abstract/database_statements.rb:279:in `transaction'
  from active_record/transactions.rb:212:in `transaction'
  from active_record/associations/collection_association.rb:134:in `transaction'
  from active_record/associations/collection_association.rb:376:in `delete_or_destroy'
  from active_record/associations/collection_association.rb:198:in `destroy'
  from active_record/autosave_association.rb:395:in `block in save_collection_association'
  from active_record/autosave_association.rb:395:in `each'
  from active_record/autosave_association.rb:395:in `save_collection_association'
  from active_record/autosave_association.rb:187:in `block in add_autosave_association_callbacks'
  from active_record/autosave_association.rb:159:in `instance_eval'
  from active_record/autosave_association.rb:159:in `block in define_non_cyclic_method'
  from active_support/callbacks.rb:429:in `block in make_lambda'
  from active_support/callbacks.rb:239:in `block in halting_and_conditional'
  from active_support/callbacks.rb:518:in `block in invoke_after'
  from active_support/callbacks.rb:518:in `each'
  from active_support/callbacks.rb:518:in `invoke_after'
  from active_support/callbacks.rb:136:in `run_callbacks'
  from active_support/callbacks.rb:827:in `_run_update_callbacks'
  from active_record/callbacks.rb:336:in `_update_record'
  from active_record/timestamp.rb:124:in `_update_record'
  from active_record/persistence.rb:906:in `create_or_update'
  from active_record/callbacks.rb:328:in `block in create_or_update'
  from active_support/callbacks.rb:135:in `run_callbacks'
  from active_support/callbacks.rb:827:in `_run_save_callbacks'
  from active_record/callbacks.rb:328:in `create_or_update'
  from active_record/timestamp.rb:129:in `create_or_update'
  from active_record/persistence.rb:470:in `save'
  from active_record/validations.rb:47:in `save'
  from active_record/transactions.rb:315:in `block in save'
  from active_record/transactions.rb:375:in `block in with_transaction_returning_status'
  from active_record/connection_adapters/abstract/database_statements.rb:279:in `transaction'
  from active_record/transactions.rb:212:in `transaction'
  from active_record/transactions.rb:366:in `with_transaction_returning_status'
  from active_record/transactions.rb:315:in `save'
  from active_record/suppressor.rb:44:in `save'
  from active_record/persistence.rb:621:in `block in update'
  from active_record/transactions.rb:375:in `block in with_transaction_returning_status'
  from active_record/connection_adapters/abstract/database_statements.rb:281:in `block in transaction'
  from active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
  from active_record/connection_adapters/abstract/transaction.rb:278:in `synchronize'
  from active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
  from active_record/connection_adapters/abstract/database_statements.rb:281:in `transaction'
  from active_record/transactions.rb:212:in `transaction'
  from active_record/transactions.rb:366:in `with_transaction_returning_status'
  from active_record/persistence.rb:619:in `update'
  from app/controllers/v2/projects_controller.rb:27:in `update'
  from action_controller/metal/basic_implicit_render.rb:6:in `send_action'
  from abstract_controller/base.rb:196:in `process_action'
  from action_controller/metal/rendering.rb:30:in `process_action'
  from abstract_controller/callbacks.rb:42:in `block in process_action'
  from active_support/callbacks.rb:112:in `block in run_callbacks'
  from i18n.rb:313:in `with_locale'
  from app/controllers/v2/api_controller.rb:32:in `switch_locale'
  from active_support/callbacks.rb:121:in `block in run_callbacks'
  from raven/integrations/rails/controller_transaction.rb:7:in `block in included'
  from active_support/callbacks.rb:121:in `instance_exec'
  from active_support/callbacks.rb:121:in `block in run_callbacks'
  from active_support/callbacks.rb:139:in `run_callbacks'
  from abstract_controller/callbacks.rb:41:in `process_action'
  from action_controller/metal/rescue.rb:22:in `process_action'
  from action_controller/metal/instrumentation.rb:33:in `block in process_action'
  from active_support/notifications.rb:180:in `block in instrument'
  from active_support/notifications/instrumenter.rb:24:in `instrument'
  from active_support/notifications.rb:180:in `instrument'
  from action_controller/metal/instrumentation.rb:32:in `process_action'
  from action_controller/metal/params_wrapper.rb:245:in `process_action'
  from active_record/railties/controller_runtime.rb:27:in `process_action'
  from abstract_controller/base.rb:136:in `process'
  from action_view/rendering.rb:39:in `process'
  from action_controller/metal.rb:191:in `dispatch'
  from action_controller/metal.rb:252:in `dispatch'
  from action_dispatch/routing/route_set.rb:51:in `dispatch'
  from action_dispatch/routing/route_set.rb:33:in `serve'
  from action_dispatch/journey/router.rb:49:in `block in serve'
  from action_dispatch/journey/router.rb:32:in `each'
  from action_dispatch/journey/router.rb:32:in `serve'
  from action_dispatch/routing/route_set.rb:837:in `call'
  from warden/jwt_auth/middleware/token_dispatcher.rb:20:in `call'
  from warden/jwt_auth/middleware/revocation_manager.rb:21:in `call'
  from rack/builder.rb:244:in `call'
  from warden/jwt_auth/middleware.rb:23:in `call'
  from warden/manager.rb:36:in `block in call'
  from warden/manager.rb:34:in `catch'
  from warden/manager.rb:34:in `call'
  from rack/etag.rb:27:in `call'
  from rack/conditional_get.rb:40:in `call'
  from rack/head.rb:12:in `call'
  from action_dispatch/middleware/callbacks.rb:27:in `block in call'
  from active_support/callbacks.rb:101:in `run_callbacks'
  from action_dispatch/middleware/callbacks.rb:26:in `call'
  from action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
  from action_dispatch/middleware/debug_exceptions.rb:32:in `call'
  from action_dispatch/middleware/show_exceptions.rb:33:in `call'
  from rails/rack/logger.rb:38:in `call_app'
  from rails/rack/logger.rb:26:in `block in call'
  from active_support/tagged_logging.rb:80:in `block in tagged'
  from active_support/tagged_logging.rb:28:in `tagged'
  from active_support/tagged_logging.rb:80:in `tagged'
  from rails/rack/logger.rb:26:in `call'
  from action_dispatch/middleware/remote_ip.rb:81:in `call'
  from request_store/middleware.rb:19:in `call'
  from action_dispatch/middleware/request_id.rb:27:in `call'
  from rack/runtime.rb:22:in `call'
  from active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
  from action_dispatch/middleware/executor.rb:14:in `call'
  from rack/sendfile.rb:110:in `call'
  from action_dispatch/middleware/host_authorization.rb:77:in `call'
  from raven/integrations/rack.rb:51:in `call'
  from rack/cors.rb:100:in `call'
  from rails/engine.rb:526:in `call'
  from puma/configuration.rb:228:in `call'
  from puma/server.rb:713:in `handle_request'
  from puma/server.rb:472:in `process_client'
  from puma/server.rb:328:in `block in run'
  from puma/thread_pool.rb:134:in `block in spawn_thread'
```

**Comment by dacin21** [comment]
Das Problem ist, dass es Invoices geben kann, die diese Projekt positions verwenden.

**Comment by dacin21** [comment]
Idee: Beim Projekt einen Button hinzufügen, mit welchen ein Service durch einen anderen ersetzt werden kann. Dieser aktualisiert dann:
- Das Projekt
- Alle erfassten Arbeitszeiten von diesem Projekt
- Alle Rechnungen von diesem Projekt

**Comment by dacin21** [comment]
Andere Idee: Die Rechunung unabhängig machen von den project positions.
- Die Abhängigkeit macht nur Probleme, wenn man ein Projekt anpassen will.
- Diese Abhängkeit ist im frontend nirgendwo sichtbar und macht sich nur dann bemerkbar, wenn man eine Rechunung aus ihrer Zeitspanne neu generiert. Somit ist sie eigentlich nur verwirrend.
- Man kann die Rechnung sowieso bereits von Hand anpassen und auch von Hand invoice_positions hinzufügen, die keine project_position haben.
Problem: Rapporte pro Rechnung brauchen die project_positions, damit nur die entsprechenden Aufwände aufgelistet werden können.

Alternative: Wenn man bei einem Projekt die project_positions löscht, wird bei der Rechnung die project_position einfach auf NULL gesetzt.
